#define APPNAME "Very Sleepy"

// Generated by gen_version.bat from git tags
#include "version.h"

// Since the VERSION string is generated from git tags,
// these should be updated only in the commits
// tagging a new version.
#define VERSION_MAJOR 0
#define VERSION_MINOR 91

#define VENDOR  "codersnotes.com"

#define APPURL  "http://www.codersnotes.com/sleepy/sleepy"

// Update this whenever backwards-incompatible changes
// are made to the profiling results file format.
#define FORMAT_VERSION "0.90"
